baseURL = 'https://gatari.dev/'
title = "gatari's blog"
languageCode = 'en-gb'
defaultContentLanguage = "en-gb"
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]

[params]
goToTop = true

[module]
[[module.imports]]
path = "github.com/hugo-sid/hugo-blog-awesome"

[markup]
[markup.highlight]
noClasses = false
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 4
ordered = false

[Languages.en-gb]
languageName = "English"
languageCode = "en-gb"
contentDir = "content/"
weight = 1

[Languages.en-gb.menu]
[[Languages.en-gb.menu.main]]
pageRef = "/"
name = 'Home'
url = '/'
weight = 10
[[Languages.en-gb.menu.main]]
pageRef = "posts"
name = 'Posts'
url = '/posts/'
weight = 20
[[Languages.en-gb.menu.main]]
pageRef = "about"
name = 'About'
url = '/about/'
weight = 30

[Languages.en-gb.params]
sitename = ""
defaultColor = "dark"
description = "offensive security research"
mainSections = ['posts']
goToTop = true
dateFormat = ""
rssFeedDescription = "summary"

[Languages.en-gb.params.author]
avatar = "avatar.jpg"                       # /assets/avatar.jpg
intro = "gatari's blog"
description = "offensive security research"

[[params.socialIcons]]
name = "github"
url = "https://github.com/gatariee"

[[params.socialIcons]]
name = "x"
url = "https://x.com/gatariee"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/zavierlee-sg/"